namespace NHClassGen {
  partial class ClassGenForm {
    /// <summary>
    /// Required designer variable.
    /// </summary>
    private System.ComponentModel.IContainer components = null;

    /// <summary>
    /// Clean up any resources being used.
    /// </summary>
    /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
    protected override void Dispose(bool disposing) {
      if (disposing && (components != null)) {
        components.Dispose();
      }
      base.Dispose(disposing);
    }

    #region Windows Form Designer generated code

    /// <summary>
    /// Required method for Designer support - do not modify
    /// the contents of this method with the code editor.
    /// </summary>
    private void InitializeComponent() {
      this.button1 = new System.Windows.Forms.Button();
      this.textBox1 = new System.Windows.Forms.TextBox();
      this.connectionStringBox = new System.Windows.Forms.TextBox();
      this.label1 = new System.Windows.Forms.Label();
      this.label2 = new System.Windows.Forms.Label();
      this.button3 = new System.Windows.Forms.Button();
      this.tableListView = new System.Windows.Forms.ListView();
      this.label3 = new System.Windows.Forms.Label();
      this.nameSpaceBox = new System.Windows.Forms.TextBox();
      this.SuspendLayout();
      // 
      // button1
      // 
      this.button1.Location = new System.Drawing.Point(540, 71);
      this.button1.Name = "button1";
      this.button1.Size = new System.Drawing.Size(150, 23);
      this.button1.TabIndex = 0;
      this.button1.Text = "3. Generate";
      this.button1.UseVisualStyleBackColor = true;
      this.button1.Click += new System.EventHandler(this.generateClasses);
      // 
      // textBox1
      // 
      this.textBox1.BackColor = System.Drawing.SystemColors.Window;
      this.textBox1.Dock = System.Windows.Forms.DockStyle.Bottom;
      this.textBox1.Location = new System.Drawing.Point(0, 373);
      this.textBox1.Multiline = true;
      this.textBox1.Name = "textBox1";
      this.textBox1.ScrollBars = System.Windows.Forms.ScrollBars.Both;
      this.textBox1.Size = new System.Drawing.Size(702, 207);
      this.textBox1.TabIndex = 1;
      this.textBox1.WordWrap = false;
      // 
      // connectionStringBox
      // 
      this.connectionStringBox.Location = new System.Drawing.Point(112, 12);
      this.connectionStringBox.Name = "connectionStringBox";
      this.connectionStringBox.Size = new System.Drawing.Size(578, 20);
      this.connectionStringBox.TabIndex = 3;
      this.connectionStringBox.Text = "Data Source=NBLUCAS\\SQLEXPRESS;Initial Catalog=PMEC2;Integrated Security=SSPI;";
      // 
      // label1
      // 
      this.label1.AutoSize = true;
      this.label1.Location = new System.Drawing.Point(12, 15);
      this.label1.Name = "label1";
      this.label1.Size = new System.Drawing.Size(94, 13);
      this.label1.TabIndex = 4;
      this.label1.Text = "Connection String:";
      // 
      // label2
      // 
      this.label2.AutoSize = true;
      this.label2.Location = new System.Drawing.Point(285, 76);
      this.label2.Name = "label2";
      this.label2.Size = new System.Drawing.Size(143, 13);
      this.label2.TabIndex = 5;
      this.label2.Text = "2. Select Tables to Generate";
      // 
      // button3
      // 
      this.button3.Location = new System.Drawing.Point(15, 71);
      this.button3.Name = "button3";
      this.button3.Size = new System.Drawing.Size(154, 23);
      this.button3.TabIndex = 6;
      this.button3.Text = "1. Fetch Tables";
      this.button3.UseVisualStyleBackColor = true;
      this.button3.Click += new System.EventHandler(this.fetchTableList);
      // 
      // tableListView
      // 
      this.tableListView.Location = new System.Drawing.Point(274, 102);
      this.tableListView.Name = "tableListView";
      this.tableListView.Size = new System.Drawing.Size(154, 254);
      this.tableListView.TabIndex = 7;
      this.tableListView.UseCompatibleStateImageBehavior = false;
      // 
      // label3
      // 
      this.label3.AutoSize = true;
      this.label3.Location = new System.Drawing.Point(12, 41);
      this.label3.Name = "label3";
      this.label3.Size = new System.Drawing.Size(98, 13);
      this.label3.TabIndex = 9;
      this.label3.Text = "Target Namespace";
      // 
      // nameSpaceBox
      // 
      this.nameSpaceBox.Location = new System.Drawing.Point(112, 38);
      this.nameSpaceBox.Name = "nameSpaceBox";
      this.nameSpaceBox.Size = new System.Drawing.Size(578, 20);
      this.nameSpaceBox.TabIndex = 8;
      this.nameSpaceBox.Text = "AutoGenerated";
      // 
      // ClassGenForm
      // 
      this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
      this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
      this.ClientSize = new System.Drawing.Size(702, 580);
      this.Controls.Add(this.label3);
      this.Controls.Add(this.nameSpaceBox);
      this.Controls.Add(this.tableListView);
      this.Controls.Add(this.button3);
      this.Controls.Add(this.label2);
      this.Controls.Add(this.label1);
      this.Controls.Add(this.connectionStringBox);
      this.Controls.Add(this.textBox1);
      this.Controls.Add(this.button1);
      this.MaximizeBox = false;
      this.MinimizeBox = false;
      this.Name = "ClassGenForm";
      this.ShowIcon = false;
      this.Text = "NHClassGen";
      this.ResumeLayout(false);
      this.PerformLayout();

    }

    #endregion

    private System.Windows.Forms.Button button1;
    private System.Windows.Forms.TextBox textBox1;
    private System.Windows.Forms.TextBox connectionStringBox;
    private System.Windows.Forms.Label label1;
    private System.Windows.Forms.Label label2;
    private System.Windows.Forms.Button button3;
    private System.Windows.Forms.ListView tableListView;
    private System.Windows.Forms.Label label3;
    private System.Windows.Forms.TextBox nameSpaceBox;
  }
}

