///////////////////////////////////////////////////////////////////////////////////
///    NHibernate Class Generator                                               ///
///    Copyright(C) 2016 Lucas Teske                                            ///
///                                                                             ///
///    This program is free software: you can redistribute it and/or modify     ///
///    it under the terms of the GNU General Public License as published by     ///
///    the Free Software Foundation, either version 3 of the License, or        ///
///    any later version.                                                       ///
///                                                                             ///
///    This program is distributed in the hope that it will be useful,          ///
///    but WITHOUT ANY WARRANTY; without even the implied warranty of           ///
///    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the              ///
///    GNU General Public License for more details.                             ///
///                                                                             ///
///    You should have received a copy of the GNU General Public license        ///
///    along with this program.If not, see<http://www.gnu.org/licenses/>.       ///
///////////////////////////////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace NHClassGen {
  static class GenTools {
    public static string GenerateClass(string tableName, List<Column> columns, bool generateEnumerator = false, string namespaceS = "AutoGenerated") {
      string className = upperFirst(tableName);
      string result = "";

      result =
        "namespace " + namespaceS + " {\r\n" +
        "  [NHibernate.Mapping.Attributes.Class(Table = \"" + tableName + "\")]\r\n" +
        "  public class " + className + " " + (generateEnumerator ? ": System.Collections.Generic.IEnumerable<string> " : "") + "{\r\n";

      // Private Fields
      result += "    #region Private Fields\r\n";
      foreach (Column c in columns) {
        result += "    private " + c.Type.Name + " _" + lowerFirst(c.Name) + ";\r\n";
      }
      result += "    #endregion\r\n";

      // Properties
      result += "    #region Properties\r\n";

      if (generateEnumerator) {
        result += "    public virtual event EventHandler<" + className + "EventArgs> OnChanged;\r\n";
      }

      foreach (Column c in columns) {
        if (c.IsAutoIncrement && c.IsId) {
          result += "    [NHibernate.Mapping.Attributes.Id(0, Name = \"" + c.Name + "\")]\r\n";
          result += "    [NHibernate.Mapping.Attributes.Generator(1, Class = \"native\"]\r\n";
        } else if (c.IsId) {
          result += "    [NHibernate.Mapping.Attributes.Id(Name = \"" + c.Name + "\")]\r\n";
        } else if (c.IsAutoIncrement) {
          result += "    [NHibernate.Mapping.Attributes.Generator(Class = \"native\"]\r\n";
        } else {
          result += "    [NHibernate.Mapping.Attributes.Property(";
          if (!c.IsNullable) {
            result += "NotNull = true, ";
          }

          if (c.Type == typeof(decimal)) {
            result += "Precision = " + c.NumericPrecision + ", ";
            result += "Scale = " + c.NumericScale + ", ";
          }

          if (c.Type == typeof(string) && c.CharacterMaximumLength != 0 && c.CharacterMaximumLength != 2147483647) {
            result += "Length = " + c.CharacterMaximumLength + ", ";
          }

          if (result[result.Length - 2] == ',') {
            result = result.Substring(0, result.Length - 2); // Trim last ,
          }

          result += ")]\r\n";
        }
        result += "    public virtual " + c.Type.Name + " " + upperFirst(c.Name) + " {\r\n";
        result += "      get { return _" + lowerFirst(c.Name) + "; }\r\n";
        if (generateEnumerator) {
          result += "      set {\r\n";
          result += "        " + c.Type.Name + " oldValue = _" + lowerFirst(c.Name) + ";\r\n";
          result += "        _" + lowerFirst(c.Name) + " = value;\r\n";
          result += "        OnChangedAction(\"" + upperFirst(c.Name) + "\", oldValue, value);\r\n";
          result += "      }\r\n";
        } else {
          result += "      set { _" + lowerFirst(c.Name) + " = value; }\r\n";
        }
        result += "    }\r\n";
      }
      result += "    #endregion\r\n";

      if (generateEnumerator) {
        result += "    #region Methods\r\n";
        result += "    public virtual System.Collections.Generic.IEnumerator<string> GetEnumerator() {\r\n";
        foreach (Column c in columns) {
          if (typeof(string).IsAssignableFrom(c.Type)) {
            result += "      yield return " + upperFirst(c.Name) + "; \r\n";
          } else {
            result += "      yield return " + upperFirst(c.Name) + ".ToString(); \r\n";
          }
        }

        result += "    }\r\n";
        result += "    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {\r\n";
        result += "      return this.GetEnumerator();\r\n";
        result += "    }\r\n";

        result += "    protected virtual void OnChangedAction(string FieldName, object oldValue, object newValue) {\r\n";
        result += "      EventHandler<" + className + "EventArgs> handler = OnChanged;\r\n";
        result += "      if (handler != null) {\r\n";
        result += "        " + className + "EventArgs eventArgs = new " + className + "EventArgs();\r\n";
        result += "        eventArgs.FieldName = FieldName;\r\n";
        result += "        eventArgs.OldValue = oldValue;\r\n";
        result += "        eventArgs.NewValue = newValue;\r\n";
        result += "        handler(this, eventArgs);\r\n";
        result += "      }";
        result += "    }";

        result += "    #endregion\r\n";
      }
      // Constructor
      result += "    #region Constructors\r\n";
      result += "    public " + className + "() {}\r\n";
      result += "    public " + className + "(";
      foreach (Column c in columns) {
        result += c.Type.Name + " " + lowerFirst(c.Name) + ", ";
      }

      if (result[result.Length - 2] == ',') {
        result = result.Substring(0, result.Length - 2); // Trim last ,
      }

      result += ") {\r\n";
      foreach (Column c in columns) {
        result += "      this._" + lowerFirst(c.Name) + " = " + lowerFirst(c.Name) + ";\r\n";
      }
      result += "    }\r\n";

      result += "    #endregion\r\n";
      result += "  }\r\n";

      if (generateEnumerator) {
        result += "  public class " + className + "EventArgs: EventArgs {\r\n";
        result += "    public string FieldName { get; set; }\r\n";
        result += "    public object OldValue { get; set; }\r\n";
        result += "    public object NewValue { get; set; }\r\n";
        result += "  }\r\n";
      }

      result += "}\r\n";
      return result;
    }


    private static string upperFirst(string s) {
      return s[0].ToString().ToUpper() + s.Substring(1);
    }

    private static string lowerFirst(string s) {
      return s[0].ToString().ToLower() + s.Substring(1);
    }
  }
}
